services:
  postgres:
    image: postgres:latest
    container_name: nest_postgres
    environment:
      POSTGRES_PASSWORD: rootpassword
      POSTGRES_DB: nestdb
      POSTGRES_USER: nestuser
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nestuser -d nestdb"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
